packages:
  - packages/*

overrides:
  esbuild: 0.27.3

allowBuilds:
  '@parcel/watcher': false
  '@tailwindcss/oxide': true
  '@vscode/vsce-sign': false
  esbuild: true
  exifreader: false
  keytar: false
  sharp: true

linkWorkspacePackages: true
